### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by Qomolang** [aaiyer/SuanShu#2]
as far as i know, SuanShu is not opensource, what is this bro?

**Comment by aaiyer** [comment]
It was apache licensed when I mirrored their code when they were releasing it a couple of years back. Looks like they have changed their business since then.
This code is old ~2012.... I put it up here as it contains some useful functions I look back at once in a while. But, this is nowhere near what they are currently offering.

**Comment by Qomolang** [comment]
I was just curious about how you could get the source code of an unopensourced project 
thank you for your response

**Comment by Qomolang** [comment]
> It was apache licensed when I mirrored their code when they were releasing it a couple of years back. Looks like they have changed their business since then.
> This code is old ~2012.... I put it up here as it contains some useful functions I look back at once in a while. But, this is nowhere near what they are currently offering.

I was just curious about how you could get the source code of an unopensourced project
thank you for your response

**Comment by aaiyer** [comment]
Was open source when I mirrored it :-)
